### ISSUE TITLE
Feature request: 15 min peak values

### ISSUE THREAD

**Issue by jschaeke** [KurtKeunen/esp8266_p1meter_belgium#1]
The telegram should now contain these values. Perhaps you can integrate these as well? 
https://community.home-assistant.io/t/dsmr-monthly-15-minute-peak-values-for-belgium/493105

**Comment by jschaeke** [comment]
Just added them and opened a PR to update this repo. 
![image](https://user-images.githubusercontent.com/13959340/221440419-3320db51-972c-48e6-8119-4ba6041c51e9.png)

**Comment by jschaeke** [comment]
Once it is merged we can close this issue.

**Comment by KurtKeunen** [comment]
Totally missed this, great addition!
